title: KMUpower Blog
email: marcel@kmupower.ch
description: >-
  Aktuelle Beitr채ge, Tipps und Praxisbeispiele rund um Digitalisierung, Power Apps, Power Automate und KI f체r KMU im DACH-Raum.
baseurl: ""
url: "https://www.kmupower.ch"
language: de

# Clean URLs f체r GitHub Pages
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# SEO defaults
keywords: [Power Apps, Power Automate, Digitalisierung, KMU, KI, Low-Code, Schweiz]

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults f체r Clean URLs
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
